<?php

declare(strict_types=1);

/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MultiAuthSampleLib\Authentication;

use Core\Utils\CoreHelper;

/**
 * Utility class for initializing ApiHeader security credentials.
 */
class ApiHeaderCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for ApiHeaderCredentialsBuilder
     *
     * @param string $token
     * @param string $apiKey
     */
    public static function init(string $token, string $apiKey): self
    {
        return new self(['token2' => $token, 'apiKey2' => $apiKey]);
    }

    /**
     * Setter for Token.
     *
     * @param string $token
     *
     * @return $this
     */
    public function token(string $token): self
    {
        $this->config['token2'] = $token;
        return $this;
    }

    /**
     * Setter for ApiKey.
     *
     * @param string $apiKey
     *
     * @return $this
     */
    public function apiKey(string $apiKey): self
    {
        $this->config['apiKey2'] = $apiKey;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
