<?php

declare(strict_types=1);

/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MultiAuthSampleLib\Authentication;

use Core\Authentication\CoreAuth;
use MultiAuthSampleLib\ConfigurationDefaults;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class ApiHeaderManager extends CoreAuth implements ApiHeaderCredentials
{
    /**
     * @var array
     */
    private $config;

    public function __construct(array $config)
    {
        $this->config = $config;
        parent::__construct(
            HeaderParam::init('token', $this->getToken())->requiredNonEmpty(),
            HeaderParam::init('api-key', $this->getApiKey())->requiredNonEmpty()
        );
    }

    /**
     * String value for token.
     */
    public function getToken(): string
    {
        return $this->config['token2'] ?? ConfigurationDefaults::TOKEN_2;
    }

    /**
     * String value for apiKey.
     */
    public function getApiKey(): string
    {
        return $this->config['apiKey2'] ?? ConfigurationDefaults::API_KEY_2;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $token
     * @param string $apiKey
     */
    public function equals(string $token, string $apiKey): bool
    {
        return $token == $this->getToken() &&
            $apiKey == $this->getApiKey();
    }
}
