<?php

declare(strict_types=1);

/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MultiAuthSampleLib\Authentication;

use MultiAuthSampleLib\ConfigurationInterface;
use CoreInterfaces\Core\Request\RequestSetterInterface;
use Core\Authentication\CoreAuth;

/**
 * Utility class for authorization and token management.
 */
class CustomAuthManager extends CoreAuth
{
    /**
     * @var ConfigurationInterface
     */
    private $client;

    public function __construct(ConfigurationInterface $client)
    {
        $this->client = $client;
        parent::__construct();
    }


    /**
     * Adds authentication parameters to request.
     */
    public function apply(RequestSetterInterface $request): void
    {
        // TODO: Add your custom authentication here
        // The following properties are available to use
        //     $this->client->getAccessToken()
        //
        // i.e Add a header through:
        //     $request->addHeader('key', 'value');
    }
}
