<?php

declare(strict_types=1);

/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MultiAuthSampleLib\Authentication;

use Core\Utils\CoreHelper;
use MultiAuthSampleLib\Models\OAuthScopeOAuthACGEnum;
use MultiAuthSampleLib\Models\OAuthToken;

/**
 * Utility class for initializing OAuthACG security credentials.
 */
class OAuthACGCredentialsBuilder
{
    /**
     * @var array
     */
    private $config;

    private function __construct(array $config)
    {
        $this->config = $config;
    }

    /**
     * Initializer for OAuthACGCredentialsBuilder
     *
     * @param string $oAuthClientId
     * @param string $oAuthClientSecret
     * @param string $oAuthRedirectUri
     */
    public static function init(string $oAuthClientId, string $oAuthClientSecret, string $oAuthRedirectUri): self
    {
        return new self([
            'oAuthClientId2' => $oAuthClientId,
            'oAuthClientSecret2' => $oAuthClientSecret,
            'oAuthRedirectUri2' => $oAuthRedirectUri
        ]);
    }

    /**
     * Setter for OAuthClientId.
     *
     * @param string $oAuthClientId
     *
     * @return $this
     */
    public function oAuthClientId(string $oAuthClientId): self
    {
        $this->config['oAuthClientId2'] = $oAuthClientId;
        return $this;
    }

    /**
     * Setter for OAuthClientSecret.
     *
     * @param string $oAuthClientSecret
     *
     * @return $this
     */
    public function oAuthClientSecret(string $oAuthClientSecret): self
    {
        $this->config['oAuthClientSecret2'] = $oAuthClientSecret;
        return $this;
    }

    /**
     * Setter for OAuthRedirectUri.
     *
     * @param string $oAuthRedirectUri
     *
     * @return $this
     */
    public function oAuthRedirectUri(string $oAuthRedirectUri): self
    {
        $this->config['oAuthRedirectUri2'] = $oAuthRedirectUri;
        return $this;
    }

    /**
     * Setter for OAuthToken.
     *
     * @param OAuthToken|null $oAuthToken
     *
     * @return $this
     */
    public function oAuthToken(?OAuthToken $oAuthToken): self
    {
        $this->config['oAuthToken2'] = $oAuthToken;
        return $this;
    }

    /**
     * Setter for OAuthScopes.
     *
     * @param string[]|null $oAuthScopes
     *
     * @return $this
     */
    public function oAuthScopes(?array $oAuthScopes): self
    {
        OAuthScopeOAuthACGEnum::checkValue($oAuthScopes);
        $this->config['oAuthScopes'] = $oAuthScopes;
        return $this;
    }

    /**
     * Setter for clock skew time in seconds applied while checking the OAuth Token expiry.
     *
     * @param int $oAuthClockSkew
     *
     * @return $this
     */
    public function oAuthClockSkew(int $oAuthClockSkew): self
    {
        $this->config['OAuthACG-ClockSkew'] = $oAuthClockSkew;
        return $this;
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }
}
