<?php

declare(strict_types=1);

/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MultiAuthSampleLib\Authentication;

use Closure;
use Exception;
use CoreInterfaces\Core\Request\TypeValidatorInterface;
use Core\Authentication\CoreAuth;
use Core\Client;
use Core\Request\Parameters\HeaderParam;
use Core\Utils\CoreHelper;
use InvalidArgumentException;
use MultiAuthSampleLib\Models\OAuthToken;
use MultiAuthSampleLib\Controllers\OAuthAuthorizationController;
use MultiAuthSampleLib\ConfigurationDefaults;

/**
 * Utility class for OAuth 2 authorization and token management
 */
class OAuthROPCGManager extends CoreAuth implements OAuthROPCGCredentials
{
    /**
     * Singleton instance of OAuth 2 API controller
     * @var OAuthAuthorizationController
     */
    private $oAuthApi;

    /**
     * @var array
     */
    private $config;

    /**
     * @var OAuthToken|null
     */
    private $internalOAuthToken;

    public function __construct(array $config)
    {
        parent::__construct();
        $this->config = $config;
        $this->internalOAuthToken = $this->getOAuthToken();
    }

    public function setClient(Client $client): void
    {
        $this->oAuthApi = new OAuthAuthorizationController($client);
    }

    /**
     * String value for oAuthClientId.
     */
    public function getOAuthClientId(): string
    {
        return $this->config['oAuthClientId3'] ?? ConfigurationDefaults::O_AUTH_CLIENT_ID_3;
    }

    /**
     * String value for oAuthClientSecret.
     */
    public function getOAuthClientSecret(): string
    {
        return $this->config['oAuthClientSecret3'] ?? ConfigurationDefaults::O_AUTH_CLIENT_SECRET_3;
    }

    /**
     * String value for oAuthUsername.
     */
    public function getOAuthUsername(): string
    {
        return $this->config['oAuthUsername3'] ?? ConfigurationDefaults::O_AUTH_USERNAME_3;
    }

    /**
     * String value for oAuthPassword.
     */
    public function getOAuthPassword(): string
    {
        return $this->config['oAuthPassword3'] ?? ConfigurationDefaults::O_AUTH_PASSWORD_3;
    }

    /**
     * OAuthToken value for oAuthToken.
     */
    public function getOAuthToken(): ?OAuthToken
    {
        $oAuthToken = $this->config['oAuthToken3'];
        if ($oAuthToken instanceof OAuthToken) {
            return clone $oAuthToken;
        }
        return ConfigurationDefaults::O_AUTH_TOKEN_3;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $oAuthClientId OAuth 2 Client ID
     * @param string $oAuthClientSecret OAuth 2 Client Secret
     * @param string $oAuthUsername OAuth 2 Resource Owner Username
     * @param string $oAuthPassword OAuth 2 Resource Owner Password
     */
    public function equals(
        string $oAuthClientId,
        string $oAuthClientSecret,
        string $oAuthUsername,
        string $oAuthPassword
    ): bool {
        return $oAuthClientId == $this->getOAuthClientId() &&
            $oAuthClientSecret == $this->getOAuthClientSecret() &&
            $oAuthUsername == $this->getOAuthUsername() &&
            $oAuthPassword == $this->getOAuthPassword();
    }

    /**
     * Clock skew time in seconds applied while checking the OAuth Token expiry.
     */
    public function getOAuthClockSkew(): int
    {
        return $this->config['OAuthROPCG-ClockSkew'] ?? ConfigurationDefaults::O_AUTH_ROPCG_CLOCK_SKEW;
    }

    /**
     * Fetch the OAuth token.
     * @param  array|null        $additionalParams  Additional parameters to send during authorization
     */
    public function fetchToken(?array $additionalParams = null): OAuthToken
    {
        //send request for access token
        $oAuthToken = $this->oAuthApi->requestTokenOAuthROPCG(
            $this->buildBasicHeader(),
            $this->getOAuthUsername() ?? "",
            $this->getOAuthPassword() ?? "",
            null,
            $additionalParams
        );

        $this->addExpiryTime($oAuthToken);

        return $oAuthToken;
    }

    /**
     * Refresh the OAuth token.
     * @param  array|null        $additionalParams Additional parameters to send during token refresh
     */
    public function refreshToken(?array $additionalParams = null): OAuthToken
    {
        //send request for token refresh
        $oAuthToken = $this->oAuthApi->refreshTokenOAuthROPCG(
            $this->buildBasicHeader(),
            $this->getOAuthToken()->getRefreshToken() ?? "",
            null,
            $additionalParams
        );

        $this->addExpiryTime($oAuthToken);

        return $oAuthToken;
    }

    /**
     * Has the OAuth token expired? If the token argument is not provided then this function will check the expiry of
     * the initial oauthToken, that's set in the client initialization.
     */
    public function isTokenExpired(?OAuthToken $token = null): bool
    {
        $token = $token ?? $this->getOAuthToken();
        if ($token == null || empty($token->getExpiry())) {
            return true;
        }
        return $token->getExpiry() < time() + $this->getOAuthClockSkew();
    }

    private function getTokenFromProvider(): ?OAuthToken
    {
        if ($this->internalOAuthToken != null && !$this->isTokenExpired($this->internalOAuthToken)) {
            return $this->internalOAuthToken;
        }
        $provider = $this->config['OAuthROPCG-TokenProvider'];
        if (is_callable($provider)) {
            $token = Closure::fromCallable($provider)($this->internalOAuthToken, $this);
        } else {
            try {
                $token = $this->internalOAuthToken == null ? $this->fetchToken() : $this->refreshToken();
            } catch (Exception $exp) {
                return $this->internalOAuthToken;
            }
        }
        $updateCallback = $this->config['OAuthROPCG-OnTokenUpdate'];
        if (is_callable($updateCallback)) {
            Closure::fromCallable($updateCallback)($token);
        }
        return $token;
    }

    /**
     * Check if client is authorized, throws exceptions when token is null or expired.
     *
     * @throws InvalidArgumentException
     */
    public function validate(TypeValidatorInterface $validator): void
    {
        $this->internalOAuthToken = $this->getTokenFromProvider();
        if ($this->internalOAuthToken == null) {
            throw new InvalidArgumentException('Client is not authorized. An OAuth token is needed to make API calls.');
        }
        if ($this->isTokenExpired($this->internalOAuthToken)) {
            throw new InvalidArgumentException('OAuth token is expired. A valid token is needed to make API calls.');
        }
        parent::__construct(
            HeaderParam::init(
                'Authorization',
                CoreHelper::getBearerAuthString($this->internalOAuthToken->getAccessToken())
            )->requiredNonEmpty()
        );
        parent::validate($validator);
    }

    /**
     * Build authorization header value for basic auth.
     */
    private function buildBasicHeader(): string
    {
        return 'Basic ' . base64_encode(
            $this->getOAuthClientId() . ':' . $this->getOAuthClientSecret()
        );
    }

    /**
     * Adds the expiry time to the given oAuthToken instance.
     */
    private function addExpiryTime(OAuthToken $oAuthToken): void
    {
        $expiresIn = $oAuthToken->getExpiresIn();
        if (empty($expiresIn)) {
            return;
        }
        $oAuthToken->setExpiry(time() + $expiresIn);
    }
}
