<?php

declare(strict_types=1);

/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MultiAuthSampleLib;

/**
 * Default values for the configuration parameters of the client.
 */
class ConfigurationDefaults
{
    public const TIMEOUT = 0;

    public const ENABLE_RETRIES = false;

    public const NUMBER_OF_RETRIES = 0;

    public const RETRY_INTERVAL = 1;

    public const BACK_OFF_FACTOR = 2;

    public const MAXIMUM_RETRY_WAIT_TIME = 0;

    public const RETRY_ON_TIMEOUT = true;

    public const HTTP_STATUS_CODES_TO_RETRY = [408, 413, 429, 500, 502, 503, 504, 521, 522, 524];

    public const HTTP_METHODS_TO_RETRY = ['GET', 'PUT'];

    public const ACCESS_TOKEN_2 = '';

    public const ENVIRONMENT = Environment::TESTING;

    public const PORT = '80';

    public const SUITES = Models\SuiteCodeEnum::HEARTS;

    public const USERNAME = '';

    public const PASSWORD = '';

    public const TOKEN = '';

    public const API_KEY = '';

    public const TOKEN_2 = '';

    public const API_KEY_2 = '';

    public const O_AUTH_CLIENT_ID = '';

    public const O_AUTH_CLIENT_SECRET = '';

    public const O_AUTH_TOKEN = null;

    public const O_AUTH_CLIENT_ID_2 = '';

    public const O_AUTH_CLIENT_SECRET_2 = '';

    public const O_AUTH_REDIRECT_URI_2 = '';

    public const O_AUTH_TOKEN_2 = null;

    public const O_AUTH_SCOPES = null;

    public const O_AUTH_CLIENT_ID_3 = '';

    public const O_AUTH_CLIENT_SECRET_3 = '';

    public const O_AUTH_USERNAME_3 = '';

    public const O_AUTH_PASSWORD_3 = '';

    public const O_AUTH_TOKEN_3 = null;

    public const ACCESS_TOKEN = '';

    public const PROXY_CONFIGURATION = [
        'port' => 0,
        'tunnel' => false,
        'address' => '',
        'auth' => ['user' => '', 'pass' => '', 'method' => CURLAUTH_BASIC]
    ];

    public const O_AUTH_CCG_CLOCK_SKEW = 0;

    public const O_AUTH_ACG_CLOCK_SKEW = 0;

    public const O_AUTH_ROPCG_CLOCK_SKEW = 0;

    /**
     * @var array Associative list of all default configurations
     */
    public const _ALL = [
        'timeout' => self::TIMEOUT,
        'enableRetries' => self::ENABLE_RETRIES,
        'numberOfRetries' => self::NUMBER_OF_RETRIES,
        'retryInterval' => self::RETRY_INTERVAL,
        'backOffFactor' => self::BACK_OFF_FACTOR,
        'maximumRetryWaitTime' => self::MAXIMUM_RETRY_WAIT_TIME,
        'retryOnTimeout' => self::RETRY_ON_TIMEOUT,
        'httpStatusCodesToRetry' => self::HTTP_STATUS_CODES_TO_RETRY,
        'httpMethodsToRetry' => self::HTTP_METHODS_TO_RETRY,
        'accessToken2' => self::ACCESS_TOKEN_2,
        'environment' => self::ENVIRONMENT,
        'port' => self::PORT,
        'suites' => self::SUITES,
        'username' => self::USERNAME,
        'password' => self::PASSWORD,
        'token' => self::TOKEN,
        'apiKey' => self::API_KEY,
        'token2' => self::TOKEN_2,
        'apiKey2' => self::API_KEY_2,
        'oAuthClientId' => self::O_AUTH_CLIENT_ID,
        'oAuthClientSecret' => self::O_AUTH_CLIENT_SECRET,
        'oAuthToken' => self::O_AUTH_TOKEN,
        'oAuthClientId2' => self::O_AUTH_CLIENT_ID_2,
        'oAuthClientSecret2' => self::O_AUTH_CLIENT_SECRET_2,
        'oAuthRedirectUri2' => self::O_AUTH_REDIRECT_URI_2,
        'oAuthToken2' => self::O_AUTH_TOKEN_2,
        'oAuthScopes' => self::O_AUTH_SCOPES,
        'oAuthClientId3' => self::O_AUTH_CLIENT_ID_3,
        'oAuthClientSecret3' => self::O_AUTH_CLIENT_SECRET_3,
        'oAuthUsername3' => self::O_AUTH_USERNAME_3,
        'oAuthPassword3' => self::O_AUTH_PASSWORD_3,
        'oAuthToken3' => self::O_AUTH_TOKEN_3,
        'accessToken' => self::ACCESS_TOKEN,
        'OAuthCCG-ClockSkew' => self::O_AUTH_CCG_CLOCK_SKEW,
        'OAuthCCG-TokenProvider' => null,
        'OAuthCCG-OnTokenUpdate' => null,
        'OAuthACG-ClockSkew' => self::O_AUTH_ACG_CLOCK_SKEW,
        'OAuthROPCG-ClockSkew' => self::O_AUTH_ROPCG_CLOCK_SKEW,
        'OAuthROPCG-TokenProvider' => null,
        'OAuthROPCG-OnTokenUpdate' => null,
        'proxyConfiguration' => self::PROXY_CONFIGURATION
    ];
}
