<?php

declare(strict_types=1);

/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MultiAuthSampleLib;

use Core\Types\Sdk\CoreCallback;
use Core\Utils\CoreHelper;
use MultiAuthSampleLib\Authentication\ApiHeaderCredentialsBuilder;
use MultiAuthSampleLib\Authentication\ApiKeyCredentialsBuilder;
use MultiAuthSampleLib\Authentication\BasicAuthCredentialsBuilder;
use MultiAuthSampleLib\Authentication\OAuthACGCredentialsBuilder;
use MultiAuthSampleLib\Authentication\OAuthBearerTokenCredentialsBuilder;
use MultiAuthSampleLib\Authentication\OAuthCCGCredentialsBuilder;
use MultiAuthSampleLib\Authentication\OAuthROPCGCredentialsBuilder;
use MultiAuthSampleLib\Proxy\ProxyConfigurationBuilder;

class MultiAuthSampleClientBuilder
{
    /**
     * @var array
     */
    private $config = [];

    /**
     * @phan-suppress PhanEmptyPrivateMethod
     */
    private function __construct()
    {
    }

    public static function init(): self
    {
        return new self();
    }

    public function getConfiguration(): array
    {
        return CoreHelper::clone($this->config);
    }

    public function timeout(int $timeout): self
    {
        $this->config['timeout'] = $timeout;
        return $this;
    }

    public function enableRetries(bool $enableRetries): self
    {
        $this->config['enableRetries'] = $enableRetries;
        return $this;
    }

    public function numberOfRetries(int $numberOfRetries): self
    {
        $this->config['numberOfRetries'] = $numberOfRetries;
        return $this;
    }

    public function retryInterval(float $retryInterval): self
    {
        $this->config['retryInterval'] = $retryInterval;
        return $this;
    }

    public function backOffFactor(float $backOffFactor): self
    {
        $this->config['backOffFactor'] = $backOffFactor;
        return $this;
    }

    public function maximumRetryWaitTime(int $maximumRetryWaitTime): self
    {
        $this->config['maximumRetryWaitTime'] = $maximumRetryWaitTime;
        return $this;
    }

    public function retryOnTimeout(bool $retryOnTimeout): self
    {
        $this->config['retryOnTimeout'] = $retryOnTimeout;
        return $this;
    }

    /**
     * @param int[] $httpStatusCodesToRetry
     *
     * @return $this
     */
    public function httpStatusCodesToRetry(array $httpStatusCodesToRetry): self
    {
        $this->config['httpStatusCodesToRetry'] = $httpStatusCodesToRetry;
        return $this;
    }

    /**
     * @param string[] $httpMethodsToRetry
     *
     * @return $this
     */
    public function httpMethodsToRetry(array $httpMethodsToRetry): self
    {
        $this->config['httpMethodsToRetry'] = $httpMethodsToRetry;
        return $this;
    }

    public function accessToken2(string $accessToken2): self
    {
        $this->config['accessToken2'] = $accessToken2;
        return $this;
    }

    public function environment(string $environment): self
    {
        $this->config['environment'] = $environment;
        return $this;
    }

    public function port(string $port): self
    {
        $this->config['port'] = $port;
        return $this;
    }

    public function suites(int $suites): self
    {
        $this->config['suites'] = $suites;
        return $this;
    }

    public function basicAuthCredentials(BasicAuthCredentialsBuilder $basicAuth): self
    {
        $this->config = array_merge($this->config, $basicAuth->getConfiguration());
        return $this;
    }

    public function apiKeyCredentials(ApiKeyCredentialsBuilder $apiKey): self
    {
        $this->config = array_merge($this->config, $apiKey->getConfiguration());
        return $this;
    }

    public function apiHeaderCredentials(ApiHeaderCredentialsBuilder $apiHeader): self
    {
        $this->config = array_merge($this->config, $apiHeader->getConfiguration());
        return $this;
    }

    public function oAuthCCGCredentials(OAuthCCGCredentialsBuilder $oAuthCCG): self
    {
        $this->config = array_merge($this->config, $oAuthCCG->getConfiguration());
        return $this;
    }

    public function oAuthACGCredentials(OAuthACGCredentialsBuilder $oAuthACG): self
    {
        $this->config = array_merge($this->config, $oAuthACG->getConfiguration());
        return $this;
    }

    public function oAuthROPCGCredentials(OAuthROPCGCredentialsBuilder $oAuthROPCG): self
    {
        $this->config = array_merge($this->config, $oAuthROPCG->getConfiguration());
        return $this;
    }

    public function oAuthBearerTokenCredentials(OAuthBearerTokenCredentialsBuilder $oAuthBearerToken): self
    {
        $this->config = array_merge($this->config, $oAuthBearerToken->getConfiguration());
        return $this;
    }

    public function httpCallback($httpCallback): self
    {
        if (!$httpCallback instanceof CoreCallback) {
            return $this;
        }
        $this->config['httpCallback'] = $httpCallback;
        return $this;
    }

    public function proxyConfiguration(ProxyConfigurationBuilder $proxyConfiguration): self
    {
        $this->config['proxyConfiguration'] = $proxyConfiguration->getConfiguration();
        return $this;
    }

    public function build(): MultiAuthSampleClient
    {
        return new MultiAuthSampleClient($this->config);
    }
}
