<?php

declare(strict_types=1);

/*
 * MultiAuthSampleLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace MultiAuthSampleLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const DEFAULT_ = 'default';

    public const AUTH = 'auth';
}
